---
# Input iteration variable: cf_space

- name: "Space - Procesing space {{ cf_space.name }} in {{ cf_space_organization }} organization"
  set_fact:
    _space_organization_name: "{{ cf_space_organization }}"
    _space_name: "{{ cf_space.name }}"
    _space_force: "{{ cf_space.force | default(cf_space_force) | default('no') }}"
    _space_state: "{{ cf_space.state | default('present') }}"
    _space_allow_ssh: "{{ cf_space.allow_ssh | default('no') }}"
    _space_security_groups: "{{ cf_space.security_groups | default([]) }}"
    _space_developers: "{{ cf_space.developers | default([]) }}"
    _space_managers: "{{ cf_space.managers | default([]) }}"
    _space_auditors: "{{ cf_space.auditors | default([]) }}"

# Clean other input variables
- name: "Space - Facts"
  set_fact:
   cf_space_organization: null
   cf_space_force: null


- name: "Space - Managing space {{ _space_organization_name }}:{{ _space_name }} {{ _space_state }}"
  cf_space:
    name: "{{ _space_name }}"
    state: "{{ _space_state }}"
    force: "{{ _space_force }}"
    allow_ssh: "{{ _space_allow_ssh }}"
    organization: "{{ _space_organization_name }}"
    admin_user: "{{ cf_admin_user }}"
    admin_password: "{{ cf_admin_password }}"
    api_url: "{{ cf_api }}"


- block:
  - name: "Space - Managing security groups for {{ _space_organization_name }}:{{ _space_name }}"
    include: secgroup.yml
      cf_secgroup="{{ _secgroup.1 }}"
      cf_secgroup_name="auto.{{ _space_organization_name }}.{{ _space_name }}.{{ _secgroup.0 }}"
      cf_secgroup_organization="{{ _space_organization_name }}"
      cf_secgroup_space="{{ _space_name }}"
      cf_secgroup_space_state="{{ _space_state }}"
    with_indexed_items: "{{ _space_security_groups }}"
    loop_control:
      loop_var: _secgroup
    delegate_to: "{{ groups.client[0] }}"
    tags: ["cf", "secgroup"]

  - name: "Space - Assigning developers to {{ _space_organization_name }}:{{ _space_name }}"
    cf_space:
      user_name: "{{ item.name }}"
      user_role: developer
      user_state: "{{ item.state | default('present') }}"
      name: "{{ _space_name }}"
      organization: "{{ _space_organization_name }}"
      admin_user: "{{ cf_admin_user }}"
      admin_password: "{{ cf_admin_password }}"
      api_url: "{{ cf_api }}"
    with_items: "{{ _space_developers }}"
    when: _space_developers

  - name: "Space - Assigning managers to space {{ _space_organization_name }}:{{ _space_name }}"
    cf_space:
      user_name: "{{ item.name }}"
      user_role: manager
      user_state: "{{ item.state | default('present') }}"
      name: "{{ _space_name }}"
      organization: "{{ _space_organization_name }}"
      admin_user: "{{ cf_admin_user }}"
      admin_password: "{{ cf_admin_password }}"
      api_url: "{{ cf_api }}"
    with_items: "{{ _space_managers }}"
    when: _space_managers

  - name: "Space - Assigning auditors to space {{ _space_organization_name }}:{{ _space_name }}"
    cf_space:
      user_name: "{{ item.name }}"
      user_role: auditor
      user_state: "{{ item.state | default('present') }}"
      name: "{{ _space_name }}"
      organization: "{{ _space_organization_name }}"
      admin_user: "{{ cf_admin_user }}"
      admin_password: "{{ cf_admin_password }}"
      api_url: "{{ cf_api }}"
    with_items: "{{ _space_auditors }}"
    when: _space_auditors

  when: _space_state == 'present'

